### ISSUE TITLE
Add [mkdocs](https://squidfunk.github.io/mkdocs-material/) so we can create a easy-to-read documentation site

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/streaming-runtimes#15]
Basic Structure of documentation for the Streaming Runtime so we have an easy way to introduce the runtime to people.

# TODO
- [x] Structure for Docs
- [x] Add Home Page
- [ ] Create Logo and Add logo
- [x] Add Tutorials
- [x] Add Installation
- [ ] Add Documentation for all the CRDs (Streams, Cluster Streams, Processors)
- [x] Add Code samples

**Comment by dolfolife** [comment]
site built already
